name: Deploy Cyreton

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 🚀 Sync Files
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: "184.174.36.72"
          REMOTE_USER: "cyretoni"
          SSH_PORT: 21098  # <--- This is likely the missing piece!
          TARGET: "/home/cyretoni/public_html"
          SOURCE: "./"
          # This bypasses the "Strict Host Key" check which causes hangs
          ARGS: "-avzr --delete -e 'ssh -p 21098 -o StrictHostKeyChecking=no'"