name: Secure SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🚀 Deploy via rsync
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./ 
          remote_path: /home/cyretoni/public_html
          remote_host: ${{ secrets.SSH_SERVER }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}